services:
  aws-glue:
    image: public.ecr.aws/glue/aws-glue-libs:5
    container_name: aws-glue
    volumes:
      - .:/home/glue
    ports:
      - "4040:4040" # Porta para UI do Spark
    stdin_open: true
    tty: true
    depends_on:
      - localstack

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG:-0}
      - SERVICES=s3
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"